### PR TITLE
SN-165 #194 Bug fixed: App.py and npm run now running and the web application running

### PR DESCRIPTION
**Pull request by deeppatel-11**

### CODE REVIEW

**Comment by abirshah** [comment]
### _Variables Name._

Looks good.

### _Function Name_

Looks good but it can be improved. In _camera.py_, line 8 function name can be improved.
 

### _Long Function._

None of this changes.

### _Code Complexity._

Just by reviewing code complexity looks good. Definitely _sonarQuebe_ will give a better answer.

### _PR Checklist_

  - [] Documentation present for every component and function.
  - [] Unit tests are implemented.
  - [x] Implementation matches the corresponding requirements.
  - [x] All commits linked to Jira ticket.
  
### _Overall Remarks._

Very good works. Nice PR description. I will approve this PR.
Thanks for fixing the bug. We are successfully running the program.

**Review by abirshah — APPROVED** [review]

**Review by JChekkouri — APPROVED** [review]
### Variables Name.

Good variable naming.

### Function Name

Function names looks good.

### Long Function.

No changes.

### Code Complexity.

Good code complexity.

### PR Checklist

- [ ] Documentation present for every component and function.

- [ ] Unit tests are implemented.

- [x] Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

### Overall Remarks.

Bug fixed and good PR description.

**Comment by BadrSaidi** [comment]
### Variables Name

Variable naming is good.

### Function Name

Function naming is good.

### Long Function

No changes.

### Code Complexity.

Code complexity looks good.

### PR Checklist

- [ ] Documentation present for every component and function.
- [ ] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

### Overall Remarks

The bug is fixed.

**Review by BadrSaidi — APPROVED** [review]

**Review by MikeG3 — COMMENTED** [review]
Variables Name
NA

Function Name
NA

Long Function
NA

Code Complexity
NA

PR Checklist
 - [ ] Documentation present for every component and function
 - [ ] Unit tests are implemented
 - [x] Implementation matches the corresponding requirements
 - [x] All commits linked to Jira ticket

Overall Remarks
camera.py - Line 11-12:
it looks like these two lines of codes are backwards, logicially. Shouldnt the camera start, then sleep for 3 seconds? Otherwise, I dont see why there is a 3 second delay here

**Comment by deeppatel-11** [comment]
@MikeG3 the 3 seconds delay is cause some cameras take time to on.

**Pull request merged**
