### PR TITLE
SN-79 SN-80 Video frame storing into server. Refactoring: Class extraction, Variable renaming

### PR DESCRIPTION
**Pull request by deeppatel-11**
This pull request contains:
- Storing video frame to the server. 
- Being able to detect cats, dogs, dogs parts, cats parts, person.
- Refactoring: renaming variables, class extraction, method extraction.

### CODE REVIEW

**Review by MikeG3 — APPROVED** [review]
### Variables Name
Good

### Function Name
camera.py: line 106 / 108
Id suggest removing the conjugatoin, for convention
addingSizeOfBoundingBoxes() / addingProportionsOfBoundingBoxes()
change to 
addSizeOfBoundingBoxes() / addProportionsOfBoundingBoxes()


### Long Function
Good refactoring


### Code Complexity
We should verify this with our tools, due to the many conditions

### PR Checklist
- [ ] Documentation present for every component and function.
- [ ] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x]  All commits linked to Jira ticket.

### Overall Remarks
Good work with this

There are a lot of conditions in this code. If we can break these conditions into functions that return Booleans, it can help make the code more readable imho

**Comment by abirshah** [comment]
### _Variables Name._

Looks good. However, it can be improved.

### _Function Name_

Looks good and no confusion in the naming functions.
 

### _Long Function._

In Camera.py, the class can be refactored more.

### _Code Complexity._

Just by reviewing code complexity seems to increase a lot. Definitely _sonarQuebe_ will give a better answer.

### _PR Checklist_

  - [] Documentation present for every component and function.
  - [] Unit tests are implemented.
  - [x] Implementation matches the corresponding requirements.
  - [x] All commits linked to Jira ticket.
  
### _Overall Remarks._

Good work.PR description looks good to me. Some good code refactoring. 
I will approve this PR.

**Review by abirshah — APPROVED** [review]

**Review by JChekkouri — APPROVED** [review]
### Variables Name

Good variables naming.

### Function Name

Function names looks good.

### Long Function.

Refactoring is good.

### Code Complexity.

Code complexity seems high, we will find out more after using SonarQuebe.

### PR Checklist

- [x] Documentation present for every component and function.

- [ ]  Unit tests are implemented.

- [x]  Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

### Overall Remarks.

Good work on this PR.

**Comment by mariemek** [comment]
### Variables Name
good

### Function Name
Function names looks good

### Long Function
Functions look good

### Code Complexity
code complexity looks good

### PR Checklist
- [ ] Documentation present for every component and function.
- [ ] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

### Overall Remarks
overall it's good

**Pull request merged**
