### PR TITLE
SN-42 SN-82 SN-93 SN-81 SN-92: Video Streaming from camera source, Storing Key object video clips, web application

### PR DESCRIPTION
**Pull request by hasan-ahmed**
**This PR closes stories SN-42 SN-82 SN-93 SN-81 SN-92**.

Screen Shot 2021-11-24 at 11 51 45 AM

Video demo link: https://drive.google.com/file/d/1E-kBBGXRhUY2DTny-teMehke2CwOwTal/view?usp=sharing

The backend of the system is stored in WebService directory. There you will find a Flask web service that interacts with the DB, interacts with AWS S3 and provides REST endpoints for our web client. 

The front end of the application is found in pet-detection-client. It is a react application built using hooks and Material UI as a UI frame work. 

**Steps to run the system:**

BACKEND:

- Make sure that you have an AWS account credentials and set your credentials in your system. This link provides details on how to do so: [Credentials Instructions](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)
- install the required python modules: pip/pip3 install -r requirements.txt
- python3 app.py

FRONTEND:

- npm install 
- npm start

### CODE REVIEW

**Comment by MikeG3** [comment]
Looks like some great progress! 
Its a lot of code, Ill take some time to look this all over

In the demo video, I see a "cat_bird_mouth" event. Was that done with a picture?

**Review by MikeG3 — COMMENTED** [review]
## Variables Name
NA

## Function Name
app.py 
- line 56: video -> Is this activating the camera? Or is this a sub-method?
- line 48 gen(camera) -> Im not entirely sure what this function does. It looks like it returns a list of frames, from the video feed. If so, perhaps we can call it frame_generator? frame_capture? ..or something that describes it more. Ideally in a way that makes it possible to eliminate comments

cam_video_stream.py
- line 14:  update -> is this restarting the camera? 
-line 20:  read -> perhaps name this "capture", "save_frame" or so, if I understand this

## Long Function
camera.py
-line 13-18 "#reading the classes.names file" -> maybe this could be defined as a method, in itself
-line 40 "# Getting the bounding boxes, confidence for each box and class ids" -> The method is long, perhaps this can also be broken into a function (ie. get_bounding_box() + set_bounding_box_colour() )

## Code Complexity
Code is moderately complex, but concise. I think it is a good balance of the 2.

## PR Checklist
- [ ] Documentation present for every component and function.
- [ ] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

## Overall Remarks
Really fantastic work and progress!!
Because this is a major section of our project, and a lot of code will be attached to this, it may be beneficial to review this with our team at our next meeting, if you are up for a small presentation?

pr.review.md
Ironically, I used the PR Review template that Sha provided. Maybe we can merge it with the template that you created?

events.py 
should be added to the class diagram, it will work well as a class that provides the correct data for notifications, as well as data storage

**Comment by hasan-ahmed** [comment]
> L

Yup! So i loaded a picture with a car with a bird in its mount on my phone and pointed it to my camera and it detected it

**Comment by hasan-ahmed** [comment]
> Looks like some great progress! Its a lot of code, Ill take some time to look this all over
> 
> In the demo video, I see a "cat_bird_mouth" event. Was that done with a picture?

Exactly, I loaded a picture of a cat with bird in mouth on my phone and pointed it at my webcam

**Comment by abirshah** [comment]
### _Variables Name._

The Variable's name should explain a little more so that when we use those variables
 in the other parts of the program, it doesn't become confusing.
Such as  In Line 26 in s3_service.py, _response_ variables, what kind of response you are capturing. 
Line 26,27 in app.py. Line 67 in camera.py 

### _Function Name_

Function naming is good but can be improved with a better naming convention.
I believe, all the previous codes used _Camel case_ for naming convention. However,
here the _Snake case_ is used for naming convention. We need to stick with one convention.
We can refactor code so that everything becomes consistent.
 

### _Long Function._

They are good. 

### _Code Complexity._

Just by reviewing code complexity looks good. Definitely _sonarQuebe_ will give a better answer.

### _PR Checklist_

  - [] Documentation present for every component and function.
  - [] Unit tests are implemented.
  - [x] Implementation matches the corresponding requirements.
  - [x] All commits linked to Jira ticket.
  
### _Overall Remarks._

Very good works. Nice PR description. I will approve this PR.
Future improvement could be refactored _camera.py_ class by adding functions.
Also, implement all the unit tests.

**Review by abirshah — APPROVED** [review]

**Review by MikeG3 — APPROVED** [review]
*Please see comment section

**Comment by BadrSaidi** [comment]
### Variables Name

These variables name could be more descriptive:
s3_service.py : Line 26

### Function Name

The functions naming is good.

### Long Function

The long functions are good.

### Code Complexity

Code complexity seems good.

### PR Checklist

- [ ] Documentation present for every component and function
- [ ] Unit tests are implemented
- [X] Implementation matches the corresponding requirements
- [X] All commits linked to Jira ticket

### Overall Remarks

You can remove the test_images directory since it doesn't seem like you are using it in your code.

**Review by BadrSaidi — APPROVED** [review]

**Comment by JChekkouri** [comment]
### Variables Name

The variables name could be a little more descriptive.

### Function Name

Clear naming for the functions.

### Long Function

Long functions are good.

### Code Complexity

Code complexity looks good.

### PR Checklist

- [ ] Documentation present for every component and function

- [ ]  Unit tests are implemented

- [x] Implementation matches the corresponding requirements

- [x]  All commits linked to Jira ticket

Overall Remarks

You can delete the templates directory and route on the flask application since we seem to be using a separate react application for the UI

**Comment by deeppatel-11** [comment]
Function Name
I agree with @abirshah about the naming convention being consistent throughout. Otherwise the names seem good.

Long Function.
Not many long functions so easy to understand the code. 
They are good.

PR Checklist

- [ ]  Documentation present for every component and function.
- [ ] Unit tests are implemented.
- [ ] Implementation matches the corresponding requirements.
- [ ]  All commits linked to Jira ticket.

Overall Remarks.
Great work overall, I think we can continue integrating new functionality on this. I approve the Pull request.

**Review by deeppatel-11 — APPROVED** [review]

**Pull request merged**
