### PR TITLE
Fixed Bug: Bird in cat's mouth bounding box appears in dog's mouth.

### PR DESCRIPTION
**Pull request by deeppatel-11**
Bug Report: https://github.com/abirshah/fullStack-Developer/issues/174
Fixed by retraining the dataset with more images for better accuracy. 
The image below shows the bug is fixed: 
image

### CODE REVIEW

**Comment by abirshah** [comment]
# Variables Name.

Line 17 _bbDictionary_ doesn't give hint about the variable.

# Function Name

Line 8, 24  function name can be more specific to what the function going to do.

# Long Function.

Line 97 _main_

# Code Complexity.

Code complexity is good so far. 

# PR Checklist 

  - [x] Documentation present for every component and function.
  - [x] Unit tests are implemented.
  - [x] Implementation matches the corresponding requirements.
  - [x] All commits linked to Jira ticket.
  
# Overall Remarks.

By restricting only in the cat images _bird in cat mouth_  appear should resolve the bug. 
Also, some nice refactoring is done. I will approve this PR and improvements can be
done in the future development process.

**Review by abirshah — APPROVED** [review]

**Review by MikeG3 — COMMENTED** [review]
## Variables Name
Sha mentioned bbDictionary.
I took me a few seconds to understand bb is bounding boxm but I understood
Dictionary, could mean a few different things. Does it refer to the type of object in the box? Or, is it a list of bounding boxes

## Function Name
gettingRatio - I usually see these functions written as "getRatio"
addingRatio - same as above. You can remove the conjugatoin "ing" and write addRatio

## Long Function
Functions look good

## Code Complexity
There are some statements, that may be simplified by creating a function.

Line 179... has a comment 'This stores the sze of each bounding box into a dictionary'
Perhaps this could be defined as a function "setBoxDimension" or something simillar


## PR Checklist
- [x] Documentation present for every component and function.
- [x] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

## Overall Remarks
Looks like the bug is fixed
Any of the above suggestions can be left to a refactoring stage of development

**Comment by BadrSaidi** [comment]
The bug is fixed.

**Comment by MikeG3** [comment]
Sorry, I accidently closed/merged this.

Ill let the rest of the team, review it

**Comment by JChekkouri** [comment]
**Variables Name.**

Maybe change the name of the variable bbDictionary so it is easier to understand

**Function Name**

Same as Mike: add and get are more common than adding and getting

**Long Function.**

The functions look good

**Code Complexity.**

Code complexity looks good

**PR Checklist**

- [x]  Documentation present for every component and function.

- [x] Unit tests are implemented.

- [x] Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

**Overall Remarks.**

The bug looks fixed, we can improve the rest in the future if needed

**Comment by BadrSaidi** [comment]
### Variables Name

Line 17: the variable name bbDictionary is not very descriptive.

### Function Name

Line 15, 24 and 35: For these functions' name, replace adding/getting by add/get.

### Long Function

Line 97: main

### Code Complexity

Code complexity is good.

### PR Checklist

- [X] Documentation present for every component and function
- [X] Unit tests are implemented
- [X] Implementation matches the corresponding requirements
- [X] All commits linked to Jira ticket

### Overall Remarks

The bug is fixed.

**Comment by mariemek** [comment]
### Variables Name
bbDictionary is a confusing variable maybe we can change it to something that clearly shows it's about the bounding box

### Function Name
we could change gettingRation to getRatio to keep uniformity with getClasses and getNumbers

### Long Function
Functions look good

### Code Complexity
code complexity look good


### PR Checklist
 - [x] Documentation present for every component and function.
 - [x] Unit tests are implemented.
 - [x] Implementation matches the corresponding requirements.
 - [x] All commits linked to Jira ticket.
 
### Overall Remarks
The above suggestions would make the code cleaner and easier to read, overall it's good

**Pull request merged**
