### PR TITLE
Mobile app is created with some of the the functionality is not. 

### PR DESCRIPTION
**Pull request by abirshah**
_**Description**_
Some of the mobile app functionality is implemented. The app is built using flutter languages.
First, You need to download flutter and set up environment variables for flutter.

To check flutter available in the system, you need to run `flutter doctor` command.
To run you need to go to the program folder and run `flutter run` command.

- User verification.
- User roles.
- Display based on user roles.
- Functionality based on user roles.

**_Document Checklist_** 
- [X] Unit test present.
- [X] Commits are linked to Jira ticket.
- [X] Implementation matches the requirements.

### CODE REVIEW

**Comment by deeppatel-11** [comment]
Variables Name.
Looks good, following the naming convention. few variable names needs to be more descrptive

Function Name
Looks good. 

Long Function.
Nearly none so that's good.

Code Complexity.
Looks good. 

PR Checklist
- [x] Documentation present for every component and function.
- [x] Unit tests are implemented.
- [x]Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

Overall Remarks.
Very good works. PR can be more descriptive, Since its only the front-end, everything looks good.
I will approve this PR.

**Comment by deeppatel-11** [comment]
Variables Name.
Looks good, following the naming convention. few variable names needs to be more descrptive

Function Name
Looks good. 

Long Function.
Nearly none so that's good.

Code Complexity.
Looks good. 

PR Checklist
- [x] Documentation present for every component and function.
- [x] Unit tests are implemented.
- [x]Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

Overall Remarks.
Very good works. PR can be more descriptive, Since it's only the front-end, everything looks good.
I will approve this PR.

**Comment by deeppatel-11** [comment]
Variables Name.
Looks good, following the naming convention. few variable names need to be more descriptive

Function Name
Looks good. 

Long Function.
Nearly none so that's good.

Code Complexity.
Looks good. 

PR Checklist
- [x] Documentation present for every component and function.
- [x] Unit tests are implemented.
- [x]Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

Overall Remarks.
Very good works. PR can be more descriptive, Since it's only the front-end, everything looks good.
I will approve this PR.

**Review by deeppatel-11 — APPROVED** [review]
Variables Name.
Looks good, following the naming convention. few variable names need to be more descriptive

Function Name
Looks good. 

Long Function.
Nearly none so that's good.

Code Complexity.
Looks good. 

PR Checklist
- [x] Documentation present for every component and function.
- [x] Unit tests are implemented.
- [x]Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

Overall Remarks.
Very good works. PR can be more descriptive, Since it's only the front-end, everything looks good.
I will approve this PR.

**Review by JChekkouri — APPROVED** [review]

**Comment by JChekkouri** [comment]
### Variables Name
Variables naming looks good.

### Function Name
Good function names.

### Long Function
Almost no long function, so it is good.

### Code Complexity
Code complexity looks good.

### PR Checklist

- [x] Documentation present for every component and function.

- [x] Unit tests are implemented.

- [x] Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

### Overall Remarks.
Good work, PR approved.

**Review by MikeG3 — APPROVED** [review]
### Variables Name
Good

### Function Name
Good

### Long Function
Good

### Code Complexity
There is a lot of code added in this Pull-Request, it would be code to discuss next meeting, and run our software to calculate this

### PR Checklist
- [x] Documentation present for every component and function.
- [x] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

### Overall Remarks.
Some .dart files missing empty line at end, I dont know if these are files included in Darts-library
A lot of comments in the code, maybe we can delete some, as needed, as we progress
Great work, lets look this over as a team, next meeting

**Review by BadrSaidi — APPROVED** [review]

**Comment by BadrSaidi** [comment]
### Variables Name

Variables naming is good.

### Function Name

Function naming is good.

### Long Function

It is good.

### Code Complexity

Code complexity seems good.

### PR Checklist

- [x] Documentation present for every component and function.
- [x] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

### Overall Remarks

Good work.

**Pull request merged**
