### PR TITLE
Feat/unit tests/hasan

### PR DESCRIPTION
**Pull request by hasan-ahmed**
This Pull Request closes #SN-142 and improves testing for stories SN-42 SN-82 SN-93 SN-81 SN-92. 

### Unit Testing
**Description**
The WebService application was refactored to be testable by using the the create_app() factory pattern so that different configurations could be given for development, testing, and production. Refactored camera.py class to take the video source as a parameter so that we can provide some stock test videos as video source instead of webcam for testing. Unit testing instantiates and uses uses SQLITE in memory database for testing. 

Test coverage of WebService flask application is at 84%.

Screen Shot 2022-01-30 at 7 00 30 AM

**New Packages Added**

- flask-unittest
- unittest
- coverage

**How To run unittests**

`python3 test.py `
`coverage run -m unittest discover`
`coverage html -i`

### UI Testing
Added UI testing for the react web app with python and selenium. The test we're kept to the basic because we are migrating the front end of the system to a Flutter Mobile Application per discussion with stake holder. The basic test cases check that the page loads with the appropriate information and that we are able to download a stored clip.

ezgif com-gif-maker

**New Packages Added**

- selenium
- unittest

**How To run UI tests**
- Download and unzip the appropriate chrome driver for your system from https://chromedriver.chromium.org/downloads
- place the chromedriver executable in fullstack-developer/pet-detection-client/drivers
- `python3 selenium-test.py -v`

Document Checklist

- [x]  Unit test present.
- [x]  Commits are linked to Jira ticket.
- [x]  Implementation matches the requirements.

### CODE REVIEW

**Review by MikeG3 — APPROVED** [review]
### Variables Name.
Great

### Function Name
Good

### Long Function
None

### Code Complexity.
Good

PR Checklist
- [x] Documentation present for every component and function.
- [x] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

Overall Remarks.
Great work, great progress
Webservice/test.py is missing an empty line at the end, and configuration.py
I will approve this PR.

**Comment by JChekkouri** [comment]
### Variables Name

Good variables name.

### Function Name

Good function names.

### Long Function

No long functions, so it is good.

### Code Complexity

Good code complexity.

### PR Checklist

- [x] Documentation present for every component and function.

- [x] Unit tests are implemented.

- [x] Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

### Overall Remarks.
Very good work PR approved.

**Review by JChekkouri — APPROVED** [review]

**Comment by deeppatel-11** [comment]
### Variables Name
Good, it's following the naming convention

### Function Name
Very descriptive

### Long Function
No long functions, so it is good.

### Code Complexity


### PR Checklist

- [x] Documentation present for every component and function.

- [x] Unit tests are implemented.

- [x] Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

### Overall Remarks.
Very good work PR approved.

**Review by deeppatel-11 — APPROVED** [review]

**Comment by abirshah** [comment]
### _Variables Name._

Looks good.

### _Function Name_

Looks good to me.

### _Long Function._
Function in Camera.py can be refactored.


### _Code Complexity._

Just by reviewing code complexity looks good. Definitely _sonarQuebe_ will give a better answer.

### _PR Checklist_

  - [x] Documentation present for every component and function.
  - [x] Unit tests are implemented.
  - [x] Implementation matches the corresponding requirements.
  - [x] All commits linked to Jira ticket.
  
### _Overall Remarks._

Very good work. One of the best PR on the team. I will approve the PR

**Review by abirshah — APPROVED** [review]

**Pull request merged**
