### PR TITLE
Bug Fixed: Detected object email notification failing the web application. #241

### PR DESCRIPTION
**Pull request by deeppatel-11**
Bug Report: #241

### CODE REVIEW

**Comment by abirshah** [comment]
### _Variables Name._

In pet_test.py files:
Line 9: variable pd can pet_detection 
Line 13: my_img can be testing_input_image.
Line 14: my_img can be resized_testing_input_image.

### _Function Name_

In notification.py files
Line 9 _sendNotificaion_ can be improved to _sendEmailNotificatonForUserDetectedPet_
LIne 18login can be improved to _loginToGamilService_

In Camera.py:
Line 36: coco_classes can be classes_in_coco_datasets
Line 41: mail_bird_classes can be mailing_package_and_bird_in_cats_mouth.
Line 52: boxes_coco can be bounding_box_in_coco_datasets_classes.
Line 53: boxes_mail_bird can be bounding_boxes_mailing_package_and_bird_in_cats_mouth

### _Long Function._

We should refactor the function in the camera.py files. 
In line 31: _get_frame()_ can be broken into 
multiple functions in a way that each function is responsible for only one task. 


### _Code Complexity._

Camera.py class becoming complex. We should start refactoring it. 

SonarCoud results are below.

image


### _PR Checklist_

  - [x] Documentation present for every component and function.
  - [ ] Unit tests are implemented.
  - [x] Implementation matches the corresponding requirements.
  - [x] All commits linked to Jira ticket.
  
### _Overall Remarks._

Approved.

**Review by abirshah — APPROVED** [review]

**Comment by JChekkouri** [comment]
### Variables Name

Some variables could be renamed for a clearer understanding:

at line 9 in pet_test.py : variable pd could be pet_detect or petDetect
at line 76 in camera.py : mail_bird_classes could be mail_or_bird_in_cats_mouth.

### Function Name

at line 18 in notification.py files: login could be improved to GmailLogin or loginGmail

### Long Functions

The get_frame() function in camera.py is quite long and could be broken down into different functions.

### Code Complexity

The camera.py is quite complex as we can see from the sonar cloud result, Deep started the refactoring of this class so it should be good.

### PR Checklist

- [x]   Documentation present for every component and function.

- [ ]   Unit tests are implemented.

- [x]   Implementation matches the corresponding requirements.

- [x]   All commits linked to Jira ticket.


Overall Remarks.

Good work, PR approved.

**Review by JChekkouri — APPROVED** [review]

**Review by MikeG3 — COMMENTED** [review]
Great. Good job with everything.

I added a few inline-comment suggestions

**Comment by mariemek** [comment]
### Variables Name
Some variables can be more specific with instances like camera.py


### Function Name
Good function naming. some can. also be more specific

### Long Functions
Good long functions


### Code Complexity
The camera.py is quite complex and should be refactored 

### PR Checklist
 

- [x] Documentation present for every component and function.

- [ ]  Unit tests are implemented.

- [x]  Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

### Overall Remarks.

Good work overall

**Review by mariemek — APPROVED** [review]

**Pull request merged**
