### PR TITLE
Access Log, Notification, Captured images in the mobile app implemented.

### PR DESCRIPTION
**Pull request by abirshah**
Users can have access to notifications, captured images, captured videos, and object detection log 
in the mobile app. User-detected pet is displayed in the app fetching the database.

Jira User Stories Link:
[SN-94](https://fullstack-developer.atlassian.net/browse/SN-94)

Screen Shot 2022-02-18 at 7 30 00 PM       Screen Shot 2022-02-18 at 7 30 22 PM
Screen Shot 2022-02-18 at 7 30 52 PM          Screen Shot 2022-02-18 at 7 31 09 PM

### CODE REVIEW

**Comment by deeppatel-11** [comment]
Variables Name.
The variable name's are very well descriptive except a few as listed below
- Pet.dart file line 8

Functions
Function names are well described.
A few long functions came divided into shorter function for better understanding.
- build(context) - line 35 in file-> NotificationPage.dart


Code Complexity.
SonarCloud shows very low code smells(2), and No vulnerabilities. So with that information, we are good to go ahead with the approval.

PR Checklist
 -[x] Documentation present for every component and function.
 -[x] Unit tests are implemented.
 -[x] Implementation matches the corresponding requirements.
 -[x] All commits linked to Jira ticket.

Overall Remarks.
I tried it on my end and works perfectly i approve the PR

**Review by deeppatel-11 — APPROVED** [review]

**Review by MikeG3 — APPROVED** [review]
### _Variables Name._
One small grammar suggestion
ServerGatewayMock.dart
Line 29: petsList --> petlist
*sorry, I know grammar correction can be annoying

### _Function Name_

### _Long Function._

### _Code Complexity._

### _PR Checklist_

  - [x] Documentation present for every component and function.
  - [x] Unit tests are implemented.
  - [x] Implementation matches the corresponding requirements.
  - [x] All commits linked to Jira ticket.
  
### _Overall Remarks._
Great work! this ap is coming together :)
I noticed that for the notifications and access info do not include the time, I think displaying the time would be a valuable feature for this app, we used "timestamp" in many of our User Stories
I noticed 3 files that would need updates if we add this feature: (Please see in code comments)
AccessInfo.dart 
Class AccessInfo add time
CapturedImageOrVideo.dart 
NotificationInfo.dart

**Comment by JChekkouri** [comment]
### Variables Name

All the variables names are precise and descriptive so it is good.

### Functions Name

Same as the variables names.

### Long Functions

No significant long functions here so we are good.

### Code Complexity.

No bugs and no vulnerabilities from SonarCloud, and also only 2 code smells. This means that the code complexity is very good.

### PR Checklist

- [x] Documentation present for every component and function.

- [x] Unit tests are implemented.

- [x] Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

### Overall Remarks.

Good work, PR approved.

**Review by JChekkouri — APPROVED** [review]

**Comment by mariemek** [comment]
### Variables Name
the variable names look good

### Functions Name
Functions look good

### Long Functions
No long functions present

### Code Complexity.
code complexity look good

### PR Checklist
 

- [x] Documentation present for every component and function.
- [x]  Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

Overall Remarks.
Good work. Overall it looks good

**Review by mariemek — APPROVED** [review]

**Pull request merged**
