### PR TITLE
Fixed Bug: #183 SN-156 Program breaks with undetected objects.

### PR DESCRIPTION
**Pull request by deeppatel-11**
Bug Report: #183
Fixed by: By adding a sys.exit() under an if statement that terminates the program if no object is detected.
The image below shows the error:
image

### CODE REVIEW

**Comment by BadrSaidi** [comment]
**Variables Name

Variables naming is good.

**Function Name

Functions naming is good.

**Long Function

Long functions are good.

**Code Complexity

Code complexity seems good.

**PR Checklist

- [x] Documentation present for every component and function
- [x] Unit tests are implemented
- [x] Implementation matches the corresponding requirements
- [x] All commits linked to Jira ticket

**Overall Remarks

The bug is fixed.

**Review by BadrSaidi — APPROVED** [review]

**Comment by JChekkouri** [comment]
### Variables Name

Variables names are good.

### Function Name

Functions naming is good.

### Long Function

Long functions are good.

### Code Complexity

Code complexity looks good.

### PR Checklist

- [ ] Documentation present for every component and function

- [ ] Unit tests are implemented

- [x]  Implementation matches the corresponding requirements

- [x]  All commits linked to Jira ticket


### Overall Remarks

The bug has been fixed.

**Comment by MikeG3** [comment]
### Variables Name
NA

### Function Name
NA

### Long Function
NA

### Code Complexity
NA

### PR Checklist

- [x] Documentation present for every component and function
- [x]  Unit tests are implemented
- [x]  Implementation matches the corresponding requirements
- [x]  All commits linked to Jira ticket

### Overall Remarks
Can line 3 be deleted? It is a blank line

The logic is good. If the program is closing at line 145, perhaps an Error indication can be printed on line 144

**Review by MikeG3 — APPROVED** [review]
Please see the comment section for review

**Review by JChekkouri — APPROVED** [review]

**Pull request merged**
