### PR TITLE
SN-90, SN-91, SN-95, SN-102, SN-103 Improving the system to train with fewer images, storing pet information into the database, Bug Fix with storing to the database

### PR DESCRIPTION
**Pull request by deeppatel-11**
Description:
The web application camera is fixed, the bug was related to storing the video of the object detected in the server. 
Additionally, Added CI-CD testing 
Bug Report: #204

### CODE REVIEW

**Review by abirshah — APPROVED** [review]

**Review by JChekkouri — APPROVED** [review]

**Comment by abirshah** [comment]
### _Variables Name._

Looks good.

### _Function Name_

Looks good. Naming is short. I think naming can be more descriptive.

### _Long Function._
Function in Camera.py can be refactored.


### _Code Complexity._

Just by reviewing code complexity looks good. Definitely _sonarQuebe_ will give a better answer.

### _PR Checklist_

  - [] Documentation present for every component and function.
  - [] Unit tests are implemented.
  - [x] Implementation matches the corresponding requirements.
  - [x] All commits linked to Jira ticket.
  
### _Overall Remarks._

Very good works. PR can be more descriptive. Need to add clickable Jira link.
I will approve this PR.

**Comment by JChekkouri** [comment]
### Variables Name.

Variables name look good.

### Function Name

Function naming looks good.

### Long Function.

Long functions appear to be good.

### Code Complexity.

Code complexity seems to be good.

### PR Checklist

- [ ] Documentation present for every component and function.

- [ ] Unit tests are implemented.

  
- [x] Implementation matches the corresponding requirements.

  
- [x] All commits linked to Jira ticket.

### Overall Remarks.

Good work, PR approved.

**Comment by mariemek** [comment]
### Variables Name.

the variable names look good

### Function Name

Functions look good

### Long Function.

Long Functions look good

### Code Complexity.

code complexity look good

### PR Checklist

- [ ]  Documentation present for every component and function.

- [ ] Unit tests are implemented.

- [x]  Implementation matches the corresponding requirements.

- [x] All commits linked to Jira ticket.

### Overall Remarks.

Good work. Overall it looks good

**Review by BadrSaidi — APPROVED** [review]

**Comment by BadrSaidi** [comment]
### Variables Name

Variables naming is good.

### Function Name

Function naming is good.

### Long Function

Long functions look good.

### Code Complexity

Code complexity seems to be good.

### PR Checklist

- [ ] Documentation present for every component and function.
- [ ] Unit tests are implemented.
- [x] Implementation matches the corresponding requirements.
- [x] All commits linked to Jira ticket.

### Overall Remarks

Good work.

**Review by mariemek — APPROVED** [review]

**Review by hasan-ahmed — APPROVED** [review]
Variables Name
Consistent variable naming

Function Name
COnsistent variable naming

Long Function
Functions broken down into appropriate size

Code Complexity
Code complexity seems to be good.

PR Checklist
 Implementation matches the corresponding requirements.
 All commits linked to Jira ticket.

**Review by MikeG3 — COMMENTED** [review]
### Variables Name
 Pet_Detection/NeutralNetwork.py - line 27: cp_callback
 The other variables have "checkpoint" in them, Id recommend changing this to "checkpoint_callback

### Function Name
Good

### Long Function
Good

### Code Complexity
Like Shah mentioned, we can use our software to calculate this and evaluate it

### PR Checklist
- [ ] Documentation present for every component and function.
- [ ] Unit tests are implemented.
- [x]  Implementation matches the corresponding requirements.
- [x]  All commits linked to Jira ticket.

 

### Overall Remarks.
 Pet_Detection/testTensor.py missing empty line at end

**Pull request merged**
